// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function LoadConfig(arg1:string):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;
