// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['client']['ClientService']['Analyze'](arg1, arg2, arg3, arg4, arg5);
}

export function CurrentContext() {
  return window['go']['client']['ClientService']['CurrentContext']();
}

export function GetAvailableFilteredResources() {
  return window['go']['client']['ClientService']['GetAvailableFilteredResources']();
}

export function GetClusters() {
  return window['go']['client']['ClientService']['GetClusters']();
}

export function GetContexts() {
  return window['go']['client']['ClientService']['GetContexts']();
}

export function GetLocalConfig() {
  return window['go']['client']['ClientService']['GetLocalConfig']();
}

export function LoadConfig(arg1) {
  return window['go']['client']['ClientService']['LoadConfig'](arg1);
}

export function Start(arg1) {
  return window['go']['client']['ClientService']['Start'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['client']['ClientService']['TestConnection'](arg1);
}
