// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Configure(arg1) {
  return window['go']['ai']['ClientService']['Configure'](arg1);
}

export function GetAIProviders() {
  return window['go']['ai']['ClientService']['GetAIProviders']();
}

export function GetCompletion(arg1, arg2) {
  return window['go']['ai']['ClientService']['GetCompletion'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['ai']['ClientService']['SetContext'](arg1);
}
