// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['cli']['TerminalService']['CloseTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function CloseTerminal2(arg1, arg2, arg3) {
  return window['go']['cli']['TerminalService']['CloseTerminal2'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['cli']['TerminalService']['Start'](arg1);
}

export function StartTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['cli']['TerminalService']['StartTerminal'](arg1, arg2, arg3, arg4);
}

export function StartTerminal2(arg1, arg2, arg3) {
  return window['go']['cli']['TerminalService']['StartTerminal2'](arg1, arg2, arg3);
}

export function StopAll() {
  return window['go']['cli']['TerminalService']['StopAll']();
}
