// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';

export function CloseTerminal(arg1:string,arg2:string):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function StartTerminal(arg1:string,arg2:string,arg3:Array<string>):Promise<types.JSResp>;
