// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAllTerminals() {
  return window['go']['cli']['TerminalService']['CloseAllTerminals']();
}

export function CloseTerminal(arg1, arg2) {
  return window['go']['cli']['TerminalService']['CloseTerminal'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['cli']['TerminalService']['Start'](arg1);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['cli']['TerminalService']['StartTerminal'](arg1, arg2, arg3);
}
