// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CloseTerminal():Promise<void>;

export function Resize(arg1:number,arg2:number):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;

export function StartTerminal():Promise<types.JSResp>;

export function WriteInput(arg1:string):Promise<void>;
