// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal() {
  return window['go']['cli']['TerminalService']['CloseTerminal']();
}

export function Resize(arg1, arg2) {
  return window['go']['cli']['TerminalService']['Resize'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['cli']['TerminalService']['Start'](arg1);
}

export function StartTerminal() {
  return window['go']['cli']['TerminalService']['StartTerminal']();
}

export function WriteInput(arg1) {
  return window['go']['cli']['TerminalService']['WriteInput'](arg1);
}
