// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['db']['DBService']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteSession(arg1) {
  return window['go']['db']['DBService']['DeleteSession'](arg1);
}

export function EditSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['db']['DBService']['EditSession'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSessionsByClusterName(arg1) {
  return window['go']['db']['DBService']['GetSessionsByClusterName'](arg1);
}

export function Start(arg1) {
  return window['go']['db']['DBService']['Start'](arg1);
}
