// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package session

import (
	"database/sql"
)

type Session struct {
	ID          int64
	ClusterName string
	Address     string
	Port        string
	Cmds        interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
